    sources:
      - Bevan.glyphs
      - Bevan-Italic.glyphs
    axisOrder:
      - ital
    familyName: "Bevan"
    stat:
      Bevan.ttf:
      - name: Italic
        tag: ital
        values:
        - name: Roman
          value: 0
          linkedValue: 1
          flags: 2
      Bevan-Italic.ttf:
      - name: Italic
        tag: ital
        values:
        - name: Italic
          value: 1
          